### PR TITLE
Check GP_Locale too

### PR DESCRIPTION
**Pull request by szepeviktor**
No code dies here! 🌞

### CODE REVIEW

**Comment by szepeviktor** [comment]
@pedro-mendonca Please take a look at this.

**Comment by pedro-mendonca** [comment]
I'm a bit skeptical about customizing the library file locales.php, wich is a copy of the GlotPress file.
That is why I've added the analyse exception.

**Comment by szepeviktor** [comment]
You added the `namespace Translation_Stats;` but missed to import `Gettext_Translations`

**Comment by szepeviktor** [comment]
There are only two additional lines in this PR.

**Comment by pedro-mendonca** [comment]
I've just added the namespace to avoid conflicts with other plugins that also include the same class file with possible different versions and content.
The `index_for_number()` is never used in this plugin, that is why it didn't ring any bell before.
The I suggest you to push those fixes to the [GlotPress file](https://github.com/GlotPress/GlotPress-WP/blob/develop/locales/locales.php).

**Comment by szepeviktor** [comment]
All right.
The only critical problem comes from namespacing this class: lack of import `use Gettext_Translations;`

**Comment by szepeviktor** [comment]
They already fix the `root_` property problem :)

**Comment by pedro-mendonca** [comment]
Yes, it's a different version right now.
I'm using a copy of the customized version in [wp.org](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php).

**Comment by szepeviktor** [comment]
>  The I suggest you to push those fixes to the [GlotPress file](https://github.com/GlotPress/GlotPress-WP/blob/develop/locales/locales.php?rgh-link-date=2020-11-17T14%3A25%3A39Z).

Done.
https://github.com/GlotPress/GlotPress-WP/pull/1206

**Comment by pedro-mendonca** [comment]
Haha, I've made a previous PR on it. Closing mine as yours look better :)

**Comment by szepeviktor** [comment]
No!!!!!!!!!!!
I've just reverted my last commit.

**Comment by pedro-mendonca** [comment]
Thanks a lot :-)

**Pull request merged**
