### PR TITLE
Allow running on PHP 8

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Almost there!
Only PHPStan dies horribly.

**Comment by szepeviktor** [comment]
Actually PHP 5.6 and 7.0 should run on xenial (as exceptions), newer PHP versions on bionic (default).
What do you think?

**Comment by pedro-mendonca** [comment]
I was waiting for [this phpstan-wordpress PR](https://github.com/szepeviktor/phpstan-wordpress/pull/25) to be released so I didn't have to ignore platform-reqs :-)

**Comment by szepeviktor** [comment]
Is `phpstan-wordpress` the only blocker?

**Comment by pedro-mendonca** [comment]
> Actually [PHP 5.6 and 7.0 should run on xenial](https://docs.travis-ci.com/user/languages/php/#php-56x---70x-support-is-available-on-precise-trusty-and-xenial-only) (as exceptions), newer PHP versions on bionic (default).
> What do you think?

Seems a good idea. What about Focal as default? Too soon?

**Comment by szepeviktor** [comment]
No Focal for Travis https://docs.travis-ci.com/user/languages/php/#php-56x---70x-support-is-available-on-precise-trusty-and-xenial-only they are cautious.

**Comment by szepeviktor** [comment]
@pedro-mendonca Seems to resolved by https://github.com/szepeviktor/phpstan-wordpress/blob/master/composer.json#L14

**Comment by pedro-mendonca** [comment]
> 
> 
> @pedro-mendonca Seems to be resolved by https://github.com/szepeviktor/phpstan-wordpress/blob/master/composer.json#L14

Yes, perfect :-)

Thank you! I'll merge and update the default build.

**Pull request merged**
